# Generated by Django 5.0.7 on 2025-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='nagoyameshi/restaurant/image/', verbose_name='画像'),
        ),
    ]
